### ISSUE TITLE
Shows in-full in [code] tags

### ISSUE THREAD

**Issue by p00lz** [Sama34/OUGC-Spoiler#2]
When used within code tags it displays the full spoiler with the show button, and not the [spoiler]content[/spoiler] code you would expect to see in code tags.

Though when used in [php] tags it works as expected

Top: [php] tags. bottom: [code] tags
![image](https://user-images.githubusercontent.com/6020172/53656219-8221a400-3c4a-11e9-9c2f-5f15751c498b.png)

**Comment by Sama34** [comment]
Thanks, I will check it later.

**Comment by Sama34** [comment]
I totally forgot about this and just recently fixed the issue. #4
